{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-rules.config-map") -}}
{{- define "ffc-sfi-rules.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  {{- if .Values.pr }}
  SITE_URL: "{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
  {{- else }}
  SITE_URL: "{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}"
  {{- end }}
{{- end -}}
