version: '3.8'

services:
  ffc-sfi-frontend:
    build:
      context: .
      target: production
    image: ffc-sfi-frontend
    container_name: ffc-sfi-frontend
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      ELIGIBILITY_QUEUE_ADDRESS: ${ELIGIBILITY_QUEUE_ADDRESS:-notset}
      AGREEMENT_QUEUE_ADDRESS: ${AGREEMENT_QUEUE_ADDRESS:-notset}
