{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-frontend.config-map") -}}
{{- define "ffc-sfi-frontend.config-map" -}}
data:
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  {{- if .Values.pr }}
  SITE_URL: "{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
  {{- else }}
  SITE_URL: "{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}"
  {{- end }}
  UPDATE_AGREEMENT_QUEUE_ADDRESS: {{ quote .Values.container.updateAgreementQueueAddress }}
  UPDATE_ELIGIBILITY_QUEUE_ADDRESS: {{ quote .Values.container.updateEligibilityQueueAddress }}
{{- end -}}
